stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo 'Building'

test_unit_job:
  stage: test
  script:
    - echo 'Testing 3'

test_integration_job:
  stage: test
  script:
    - echo 'Testing 4'

deploy_job:
  stage: deploy
  script:
    - echo 'Deploy'
