global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#mikhail_zabolotnov'
