comment:
  image:
    repository: mzabolotnov/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: mzabolotnov/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: mzabolotnov/ui
    tag: latest
  service:
    externalPort: 9292
